# Generated by Django 4.1.7 on 2023-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.IntegerField()),
                ('a_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'acne',
            },
        ),
        migrations.CreateModel(
            name='oily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('o_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'oily',
            },
        ),
    ]
