# Generated by Django 4.1.7 on 2023-04-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_acne_oily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acne',
            old_name='a_name',
            new_name='d_name',
        ),
        migrations.RenameField(
            model_name='oily',
            old_name='o_name',
            new_name='d_name',
        ),
    ]
